services:
  api:
    image: trackfi-api:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      THC_PATH: /actuator/health
      THC_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ''
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 1s
      timeout: 4s
      retries: 5
